### ISSUE TITLE
WSC: WFschemaUpdate()

### ISSUE THREAD

**Issue by remiges-sachin** [remiges-tech/crux#35]

**Comment by remiges-Tushar** [comment]
- implemented a transition process for schema updates to minimize downtime
- added row locking to prevent concurrent modifications
- added custom validation to ensure data integrity
- added automated test cases #34 #35 #37
![WhatsApp Image 2024-02-05 at 8 39 08 PM](https://github.com/remiges-tech/crux/assets/147162924/e14579f2-8ffe-4db9-9818-7170ff8d2a6f)
